// <auto-generated />
using Fall2022_APIWorkshop;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Fall2022_APIWorkshop.Migrations
{
    [DbContext(typeof(VideoGameContext))]
    partial class VideoGameContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Fall2022_APIWorkshop.Models.MainCharacter", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("VideoGameId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("VideoGameId")
                        .IsUnique();

                    b.ToTable("MainCharacters");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Mario",
                            VideoGameId = 1
                        },
                        new
                        {
                            Id = 2,
                            Name = "Kirby",
                            VideoGameId = 2
                        },
                        new
                        {
                            Id = 3,
                            Name = "Captain Olimar",
                            VideoGameId = 3
                        });
                });

            modelBuilder.Entity("Fall2022_APIWorkshop.Models.Studio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("EmployeeCount")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Studios");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            EmployeeCount = 6717,
                            Name = "Nintendo"
                        },
                        new
                        {
                            Id = 2,
                            EmployeeCount = 202,
                            Name = "Hal Laboratories"
                        });
                });

            modelBuilder.Entity("Fall2022_APIWorkshop.Models.VideoGame", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("StudioId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("StudioId");

                    b.ToTable("VideoGames");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            StudioId = 1,
                            Title = "Super Mario Brothers"
                        },
                        new
                        {
                            Id = 2,
                            StudioId = 2,
                            Title = "Kirby: Nightmare in Dreamland"
                        },
                        new
                        {
                            Id = 3,
                            StudioId = 1,
                            Title = "Pikmin"
                        });
                });

            modelBuilder.Entity("Fall2022_APIWorkshop.Models.MainCharacter", b =>
                {
                    b.HasOne("Fall2022_APIWorkshop.Models.VideoGame", "VideoGame")
                        .WithOne("MainCharacter")
                        .HasForeignKey("Fall2022_APIWorkshop.Models.MainCharacter", "VideoGameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("VideoGame");
                });

            modelBuilder.Entity("Fall2022_APIWorkshop.Models.VideoGame", b =>
                {
                    b.HasOne("Fall2022_APIWorkshop.Models.Studio", "Studio")
                        .WithMany("VideoGames")
                        .HasForeignKey("StudioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Studio");
                });

            modelBuilder.Entity("Fall2022_APIWorkshop.Models.Studio", b =>
                {
                    b.Navigation("VideoGames");
                });

            modelBuilder.Entity("Fall2022_APIWorkshop.Models.VideoGame", b =>
                {
                    b.Navigation("MainCharacter")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
